import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose'
import { Document, Types } from 'mongoose'

export type AnalyticsReportDocument = AnalyticsReport & Document

/**
 * Rapor Tipi
 */
export enum ReportType {
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
  QUARTERLY = 'quarterly',
  CUSTOM = 'custom',
  CAMPAIGN = 'campaign',
}

/**
 * Platform Metrikleri
 */
@Schema({ _id: false })
export class PlatformMetrics {
  @Prop({ required: false, default: 0 })
  followersGained: number

  @Prop({ required: false, default: 0 })
  followersLost: number

  @Prop({ required: false, default: 0 })
  netFollowersChange: number

  @Prop({ required: false, default: 0 })
  totalPosts: number

  @Prop({ required: false, default: 0 })
  totalLikes: number

  @Prop({ required: false, default: 0 })
  totalComments: number

  @Prop({ required: false, default: 0 })
  totalShares: number

  @Prop({ required: false, default: 0 })
  totalSaves: number

  @Prop({ required: false, default: 0 })
  totalReach: number

  @Prop({ required: false, default: 0 })
  totalImpressions: number

  @Prop({ required: false, default: 0 })
  engagementRate: number // Yüzde olarak (örn: 3.5 = %3.5)

  @Prop({ required: false, default: 0 })
  avgLikesPerPost: number

  @Prop({ required: false, default: 0 })
  avgCommentsPerPost: number

  @Prop({ required: false, default: 0 })
  bestPerformingPostId?: Types.ObjectId

  @Prop({ required: false, default: 0 })
  worstPerformingPostId?: Types.ObjectId
}

/**
 * AI Önerileri ve İçgörüler
 */
@Schema({ _id: false })
export class AIInsights {
  @Prop({ required: false, default: [] })
  topPerformingContentTypes: string[] // En iyi performans gösteren içerik türleri

  @Prop({ required: false, default: [] })
  bestPostingTimes: Date[] // En iyi yayın zamanları

  @Prop({ required: false, default: [] })
  recommendedHashtags: string[] // Önerilen hashtag'ler

  @Prop({ required: false, default: [] })
  growthOpportunities: string[] // Büyüme fırsatları

  @Prop({ required: false, default: [] })
  areasForImprovement: string[] // İyileştirme alanları

  @Prop({ required: false })
  summary?: string // AI tarafından oluşturulan özet rapor metni

  @Prop({ required: false, min: 0, max: 100 })
  overallScore?: number // Genel performans skoru (0-100)
}

/**
 * Rakip Karşılaştırması
 */
@Schema({ _id: false })
export class CompetitorComparison {
  @Prop({ required: false })
  competitorName?: string

  @Prop({ required: false, default: 0 })
  theirFollowers?: number

  @Prop({ required: false, default: 0 })
  theirEngagementRate?: number

  @Prop({ required: false, default: 0 })
  followerDifference: number // Bizim takipçi - onların takipçi

  @Prop({ required: false, default: 0 })
  engagementDifference: number // Bizim etkileşim - onların etkileşim

  @Prop({ required: false })
  insights?: string // AI karşılaştırma analizi
}

@Schema({ timestamps: true })
export class AnalyticsReport {
  /**
   * Organizasyon ID
   */
  @Prop({ type: Types.ObjectId, ref: 'Organization', required: true, index: true })
  organizationId: Types.ObjectId

  /**
   * Rapor Tipi
   */
  @Prop({ required: true, enum: ReportType, default: ReportType.WEEKLY })
  reportType: ReportType

  /**
   * Rapor Dönemi
   */
  @Prop({ required: true })
  periodStart: Date

  @Prop({ required: true })
  periodEnd: Date

  /**
   * İlgili Hesap ID (Tek hesap raporu için)
   * Boşsa tüm hesaplar
   */
  @Prop({ type: Types.ObjectId, ref: 'Account', default: null })
  accountId?: Types.ObjectId | null

  /**
   * Platform Metrikleri (Platform bazlı)
   */
  @Prop({ type: Map, of: () => PlatformMetrics, default: {} })
  platformMetrics: Map<string, PlatformMetrics>

  /**
   * Toplam Metrikler (Tüm platformlar birleşik)
   */
  @Prop({ required: false, default: {} })
  totalMetrics: PlatformMetrics

  /**
   * AI İçgörüleri
   */
  @Prop({ type: () => AIInsights, required: false, default: {} })
  aiInsights: AIInsights

  /**
   * Rakip Karşılaştırmaları
   */
  @Prop({ type: [() => CompetitorComparison], default: [] })
  competitorComparisons: CompetitorComparison[]

  /**
   * PDF Rapor URL'si
   */
  @Prop({ required: false })
  pdfUrl?: string

  /**
   * Müşteriye Gönderildi mi?
   */
  @Prop({ required: true, default: false })
  emailedToClient: boolean

  /**
   * Gönderilen E-postalar
   */
  @Prop([String])
  sentToEmails: string[]

  /**
   * Son Gönderilme Tarihi
   */
  @Prop({ required: false })
  lastEmailedAt?: Date

  /**
   * Raporu Oluşturan Kullanıcı/Sistem
   */
  @Prop({ type: Types.ObjectId, ref: 'User', default: null })
  generatedBy?: Types.ObjectId | null

  /**
   * Otomatik oluşturuldu mu? (Scheduled job)
   */
  @Prop({ required: true, default: false })
  isAutoGenerated: boolean

  /**
   * Görüntülenme Sayısı (Müşteri portalında)
   */
  @Prop({ required: false, default: 0 })
  viewCount: number

  /**
   * Son Görüntülenme Tarihi
   */
  @Prop({ required: false })
  lastViewedAt?: Date

  /**
   * Özel Notlar
   */
  @Prop({ required: false })
  notes?: string

  /**
   * Ek Dosyalar
   */
  @Prop([String])
  attachments: string[]
}

export const AnalyticsReportSchema = SchemaFactory.createForClass(AnalyticsReport)

// Indexler
AnalyticsReportSchema.index({ organizationId: 1, reportType: 1, periodStart: -1 })
AnalyticsReportSchema.index({ organizationId: 1, accountId: 1, periodStart: -1 })
AnalyticsReportSchema.index({ organizationId: 1, isAutoGenerated: 1, periodEnd: 1 }) // Otomatik raporlar için
AnalyticsReportSchema.index({ emailedToClient: 1, periodEnd: 1 }) // Gönderilmemiş raporlar için
